import { sql, type Kysely } from 'kysely';

// [table, column, referenced table]. Each references the primary key. No ON DELETE CASCADE:
// nothing important is deleted, so a delete that would orphan rows fails instead.
const FOREIGN_KEYS: readonly (readonly [string, string, string])[] = [
  ['branches', 'tenant_id', 'tenants'],
  ['users', 'tenant_id', 'tenants'],
  ['roles', 'tenant_id', 'tenants'],
  ['role_permissions', 'tenant_id', 'tenants'],
  ['role_permissions', 'role_id', 'roles'],
  ['role_permissions', 'permission_code', 'permissions'],
  ['user_assignments', 'tenant_id', 'tenants'],
  ['user_assignments', 'user_id', 'users'],
  ['user_assignments', 'branch_id', 'branches'],
  ['user_assignments', 'role_id', 'roles'],
  ['devices', 'tenant_id', 'tenants'],
  ['devices', 'branch_id', 'branches'],
  ['devices', 'revoked_by', 'users'],
  ['pairing_codes', 'tenant_id', 'tenants'],
  ['pairing_codes', 'branch_id', 'branches'],
  ['pairing_codes', 'created_by', 'users'],
  ['subscriptions', 'tenant_id', 'tenants'],
  ['subscriptions', 'plan_id', 'plans'],
  ['subscriptions', 'plan_price_id', 'plan_prices'],
  ['invoices', 'tenant_id', 'tenants'],
  ['invoices', 'subscription_id', 'subscriptions'],
  ['invoices', 'paid_manually_by', 'platform_users'],
  ['invoice_lines', 'tenant_id', 'tenants'],
  ['invoice_lines', 'invoice_id', 'invoices'],
  ['plan_prices', 'plan_id', 'plans'],
  ['billing_customers', 'tenant_id', 'tenants'],
  ['payment_methods', 'tenant_id', 'tenants'],
  ['payment_methods', 'billing_customer_id', 'billing_customers'],
  ['payment_events', 'tenant_id', 'tenants'],
  ['payment_events', 'invoice_id', 'invoices'],
  ['credit_notes', 'tenant_id', 'tenants'],
  ['credit_notes', 'invoice_id', 'invoices'],
  ['credit_notes', 'issued_by', 'platform_users'],
  ['register_sessions', 'tenant_id', 'tenants'],
  ['register_sessions', 'branch_id', 'branches'],
  ['register_sessions', 'opened_by', 'users'],
  ['register_sessions', 'closed_by', 'users'],
  ['register_sessions', 'approved_by', 'users'],
  ['register_sessions', 'device_id', 'devices'],
  ['cash_counts', 'tenant_id', 'tenants'],
  ['cash_counts', 'session_id', 'register_sessions'],
  ['cash_movements', 'tenant_id', 'tenants'],
  ['cash_movements', 'session_id', 'register_sessions'],
  ['cash_movements', 'user_id', 'users'],
  ['cash_movements', 'approved_by', 'users'],
  ['cash_movements', 'device_id', 'devices'],
  ['sales', 'tenant_id', 'tenants'],
  ['sales', 'branch_id', 'branches'],
  ['sales', 'session_id', 'register_sessions'],
  ['sales', 'cashier_id', 'users'],
  ['sales', 'voided_by', 'users'],
  ['sales', 'device_id', 'devices'],
  ['sale_lines', 'tenant_id', 'tenants'],
  ['sale_lines', 'sale_id', 'sales'],
  ['sale_lines', 'product_id', 'products'],
  ['sale_line_modifiers', 'tenant_id', 'tenants'],
  ['sale_line_modifiers', 'sale_line_id', 'sale_lines'],
  ['sale_line_modifiers', 'modifier_id', 'modifiers'],
  ['sale_discounts', 'tenant_id', 'tenants'],
  ['sale_discounts', 'sale_id', 'sales'],
  ['sale_discounts', 'approved_by', 'users'],
  ['payments', 'tenant_id', 'tenants'],
  ['payments', 'sale_id', 'sales'],
  ['refunds', 'tenant_id', 'tenants'],
  ['refunds', 'sale_id', 'sales'],
  ['refunds', 'requested_by', 'users'],
  ['refunds', 'approved_by', 'users'],
  ['refund_lines', 'tenant_id', 'tenants'],
  ['refund_lines', 'refund_id', 'refunds'],
  ['refund_lines', 'sale_line_id', 'sale_lines'],
  ['discount_rules', 'tenant_id', 'tenants'],
  ['discount_rules', 'role_id', 'roles'],
  ['tenant_payment_methods', 'tenant_id', 'tenants'],
  ['categories', 'tenant_id', 'tenants'],
  ['products', 'tenant_id', 'tenants'],
  ['products', 'category_id', 'categories'],
  ['products', 'updated_by', 'users'],
  ['modifier_groups', 'tenant_id', 'tenants'],
  ['modifiers', 'tenant_id', 'tenants'],
  ['modifiers', 'group_id', 'modifier_groups'],
  ['product_modifier_groups', 'tenant_id', 'tenants'],
  ['product_modifier_groups', 'product_id', 'products'],
  ['product_modifier_groups', 'modifier_group_id', 'modifier_groups'],
  ['recipe_lines', 'tenant_id', 'tenants'],
  ['recipe_lines', 'product_id', 'products'],
  ['recipe_lines', 'inventory_item_id', 'inventory_items'],
  ['modifier_recipe_lines', 'tenant_id', 'tenants'],
  ['modifier_recipe_lines', 'modifier_id', 'modifiers'],
  ['modifier_recipe_lines', 'inventory_item_id', 'inventory_items'],
  ['inventory_items', 'tenant_id', 'tenants'],
  ['item_branch_settings', 'tenant_id', 'tenants'],
  ['item_branch_settings', 'item_id', 'inventory_items'],
  ['item_branch_settings', 'branch_id', 'branches'],
  ['item_branch_settings', 'default_supplier_id', 'suppliers'],
  ['batches', 'tenant_id', 'tenants'],
  ['batches', 'branch_id', 'branches'],
  ['batches', 'item_id', 'inventory_items'],
  ['batches', 'receipt_line_id', 'goods_receipt_lines'],
  ['stock_movements', 'tenant_id', 'tenants'],
  ['stock_movements', 'branch_id', 'branches'],
  ['stock_movements', 'item_id', 'inventory_items'],
  ['stock_movements', 'batch_id', 'batches'],
  ['stock_movements', 'user_id', 'users'],
  ['stock_movements', 'approved_by', 'users'],
  ['stock_movements', 'device_id', 'devices'],
  ['stock_counts', 'tenant_id', 'tenants'],
  ['stock_counts', 'branch_id', 'branches'],
  ['stock_counts', 'counted_by', 'users'],
  ['stock_count_lines', 'tenant_id', 'tenants'],
  ['stock_count_lines', 'count_id', 'stock_counts'],
  ['stock_count_lines', 'item_id', 'inventory_items'],
  ['suppliers', 'tenant_id', 'tenants'],
  ['supplier_items', 'tenant_id', 'tenants'],
  ['supplier_items', 'supplier_id', 'suppliers'],
  ['supplier_items', 'item_id', 'inventory_items'],
  ['purchase_orders', 'tenant_id', 'tenants'],
  ['purchase_orders', 'branch_id', 'branches'],
  ['purchase_orders', 'supplier_id', 'suppliers'],
  ['purchase_orders', 'created_by', 'users'],
  ['purchase_orders', 'approved_by', 'users'],
  ['purchase_order_lines', 'tenant_id', 'tenants'],
  ['purchase_order_lines', 'po_id', 'purchase_orders'],
  ['purchase_order_lines', 'item_id', 'inventory_items'],
  ['goods_receipts', 'tenant_id', 'tenants'],
  ['goods_receipts', 'branch_id', 'branches'],
  ['goods_receipts', 'supplier_id', 'suppliers'],
  ['goods_receipts', 'po_id', 'purchase_orders'],
  ['goods_receipts', 'received_by', 'users'],
  ['goods_receipt_lines', 'tenant_id', 'tenants'],
  ['goods_receipt_lines', 'receipt_id', 'goods_receipts'],
  ['goods_receipt_lines', 'po_line_id', 'purchase_order_lines'],
  ['goods_receipt_lines', 'item_id', 'inventory_items'],
  ['alerts', 'tenant_id', 'tenants'],
  ['alerts', 'branch_id', 'branches'],
  ['alerts', 'item_id', 'inventory_items'],
  ['alerts', 'batch_id', 'batches'],
  ['alert_reads', 'tenant_id', 'tenants'],
  ['alert_reads', 'alert_id', 'alerts'],
  ['alert_reads', 'user_id', 'users'],
  ['notification_settings', 'tenant_id', 'tenants'],
  ['notification_deliveries', 'tenant_id', 'tenants'],
  ['notification_deliveries', 'alert_id', 'alerts'],
  ['notification_deliveries', 'user_id', 'users'],
  ['audit_log', 'tenant_id', 'tenants'],
  ['audit_log', 'branch_id', 'branches'],
  ['audit_log', 'user_id', 'users'],
  ['audit_log', 'device_id', 'devices'],
  ['platform_users', 'role_id', 'platform_roles'],
  ['platform_role_permissions', 'role_id', 'platform_roles'],
  ['platform_role_permissions', 'permission_code', 'platform_permissions'],
  ['support_access_grants', 'tenant_id', 'tenants'],
  ['support_access_grants', 'staff_id', 'platform_users'],
  ['support_access_grants', 'ticket_id', 'support_tickets'],
  ['support_access_grants', 'approved_by', 'users'],
  ['platform_audit_log', 'staff_id', 'platform_users'],
  ['platform_audit_log', 'target_tenant_id', 'tenants'],
  ['platform_audit_log', 'grant_id', 'support_access_grants'],
  ['tenant_events', 'tenant_id', 'tenants'],
  ['tenant_events', 'staff_id', 'platform_users'],
  ['data_requests', 'tenant_id', 'tenants'],
  ['data_requests', 'requested_by', 'users'],
  ['data_requests', 'identity_checked_by', 'platform_users'],
  ['data_requests', 'completed_by', 'platform_users'],
  ['tenant_feature_overrides', 'tenant_id', 'tenants'],
  ['tenant_feature_overrides', 'flag_key', 'feature_flags'],
  ['tenant_feature_overrides', 'set_by', 'platform_users'],
  ['app_releases', 'released_by', 'platform_users'],
  ['device_error_reports', 'tenant_id', 'tenants'],
  ['device_error_reports', 'device_id', 'devices'],
  ['announcements', 'created_by', 'platform_users'],
  ['announcement_reads', 'tenant_id', 'tenants'],
  ['announcement_reads', 'announcement_id', 'announcements'],
  ['announcement_reads', 'user_id', 'users'],
  ['support_tickets', 'tenant_id', 'tenants'],
  ['support_tickets', 'requester_id', 'users'],
  ['support_tickets', 'assignee_id', 'platform_users'],
  ['support_tickets', 'device_id', 'devices'],
  ['support_ticket_messages', 'tenant_id', 'tenants'],
  ['support_ticket_messages', 'ticket_id', 'support_tickets'],
  ['support_ticket_messages', 'author_user_id', 'users'],
  ['support_ticket_messages', 'author_staff_id', 'platform_users'],
];

function constraintName(table: string, column: string): string {
  return `${table}_${column}_fkey`;
}

export async function up(db: Kysely<unknown>): Promise<void> {
  const statements = FOREIGN_KEYS.map(
    ([table, column, references]) =>
      `ALTER TABLE ${table} ADD CONSTRAINT ${constraintName(table, column)} FOREIGN KEY (${column}) REFERENCES ${references};`,
  );
  await sql.raw(statements.join('\n')).execute(db);
}

export async function down(db: Kysely<unknown>): Promise<void> {
  const statements = FOREIGN_KEYS.map(
    ([table, column]) => `ALTER TABLE ${table} DROP CONSTRAINT ${constraintName(table, column)};`,
  );
  await sql.raw(statements.join('\n')).execute(db);
}
