/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlertReads {
  alert_id: string;
  read_at: Timestamp;
  tenant_id: string;
  user_id: string;
}

export interface Alerts {
  batch_id: string | null;
  branch_id: string;
  id: Generated<string>;
  item_id: string;
  resolved_at: Timestamp | null;
  resolved_by_source: string | null;
  resolved_ref: string | null;
  snoozed_until: Timestamp | null;
  started_at: Timestamp;
  status: string;
  synced_at: Timestamp;
  tenant_id: string;
  type: string;
}

export interface AnnouncementReads {
  announcement_id: string;
  dismissed_at: Timestamp;
  tenant_id: string;
  user_id: string;
}

export interface Announcements {
  audience: string;
  body: string;
  created_by: string;
  ends_at: Timestamp | null;
  id: Generated<string>;
  plan_ids: string[] | null;
  send_at: Timestamp;
  send_email: boolean;
  show_banner: boolean;
  status: string;
  tenant_ids: string[] | null;
  title: string;
}

export interface AppReleases {
  min_required_from: Timestamp | null;
  notes: string;
  released_at: Timestamp;
  released_by: string;
  version: string;
  warn_from: Timestamp | null;
}

export interface AuditLog {
  action_code: string;
  after: Json | null;
  before: Json | null;
  branch_id: string | null;
  client_created_at: Timestamp;
  device_id: string | null;
  entity_id: string;
  entity_type: string;
  happened_at: Timestamp;
  id: Generated<string>;
  is_sensitive: boolean;
  sentence: string;
  synced_at: Timestamp | null;
  tenant_id: string;
  user_id: string | null;
}

export interface AuthTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: string;
  tenant_id: string;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Batches {
  batch_code: string;
  branch_id: string;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  item_id: string;
  qty_received: Numeric;
  qty_remaining: Numeric;
  receipt_line_id: string | null;
  received_at: Generated<Timestamp>;
  tenant_id: string;
  unit_cost: Numeric;
}

export interface BillingCustomers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  provider: string;
  provider_customer_id: string;
  tenant_id: string;
}

export interface Branches {
  address: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: boolean;
  name: string;
  tenant_id: string;
}

export interface CashCounts {
  count: number;
  denomination: number;
  id: Generated<string>;
  session_id: string;
  tenant_id: string;
}

export interface CashMovements {
  amount: number;
  approved_by: string | null;
  client_created_at: Timestamp;
  device_id: string | null;
  direction: string;
  id: Generated<string>;
  reason: string;
  session_id: string;
  synced_at: Timestamp | null;
  tenant_id: string;
  user_id: string;
}

export interface Categories {
  expiry_warn_days: number | null;
  id: Generated<string>;
  name: string;
  sort_order: number;
  tenant_id: string;
}

export interface CreditNotes {
  amount: number;
  id: Generated<string>;
  invoice_id: string;
  issued_at: Generated<Timestamp>;
  issued_by: string;
  number: string;
  reason: string;
  tenant_id: string;
}

export interface DataRequests {
  completed_at: Timestamp | null;
  completed_by: string | null;
  due_at: Timestamp;
  export_url: string | null;
  id: Generated<string>;
  identity_checked_by: string | null;
  received_at: Generated<Timestamp>;
  requested_by: string;
  status: string;
  tenant_id: string;
  type: string;
}

export interface DeviceErrorReports {
  app_version: string;
  client_created_at: Timestamp;
  context: Json;
  device_id: string | null;
  error_code: string;
  id: Generated<string>;
  message: string;
  synced_at: Timestamp | null;
  tenant_id: string;
}

export interface Devices {
  app_version: string;
  branch_id: string;
  id: Generated<string>;
  last_sync_at: Timestamp | null;
  license_expires_at: Timestamp;
  model: string;
  name: string;
  paired_at: Generated<Timestamp>;
  printer: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  tenant_id: string;
}

export interface DiscountRules {
  id: Generated<string>;
  max_amount: number | null;
  max_percent: Numeric | null;
  percent: Numeric;
  requires_id: boolean;
  role_id: string | null;
  tenant_id: string;
  type: string;
  vat_exempt: boolean;
}

export interface FeatureFlags {
  created_at: Generated<Timestamp>;
  description: string;
  key: string;
  plan_ids: string[] | null;
  rollout: string;
}

export interface GoodsReceiptLines {
  batch_code: string | null;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  item_id: string;
  po_line_id: string | null;
  qty_received: Numeric;
  receipt_id: string;
  tenant_id: string;
  unit_cost: number;
}

export interface GoodsReceipts {
  branch_id: string;
  closed_short: boolean;
  dr_number: string | null;
  id: Generated<string>;
  po_id: string | null;
  received_at: Generated<Timestamp>;
  received_by: string;
  supplier_id: string;
  tenant_id: string;
  total: number;
}

export interface InventoryItems {
  barcode: string | null;
  base_unit: string;
  default_shelf_days: number | null;
  id: Generated<string>;
  is_perishable: boolean;
  kind: string;
  name: string;
  pack_size: Numeric;
  pack_unit: string;
  tenant_id: string;
}

export interface InvoiceLines {
  amount: number;
  description: string;
  id: Generated<string>;
  invoice_id: string;
  qty: number;
  tenant_id: string;
  unit_amount: number;
}

export interface Invoices {
  due_at: Timestamp;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  number: string;
  paid_at: Timestamp | null;
  paid_manually_by: string | null;
  payment_link_url: string | null;
  pdf_url: string;
  period_end: Timestamp;
  period_start: Timestamp;
  provider: string;
  provider_invoice_id: string | null;
  status: string;
  subscription_id: string;
  subtotal: number;
  tenant_id: string;
  total: number;
  vat_amount: number;
}

export interface ItemBranchSettings {
  avg_cost: Numeric;
  branch_id: string;
  default_supplier_id: string | null;
  item_id: string;
  last_cost: Numeric;
  on_hand: Numeric;
  order_up_to: Numeric | null;
  reorder_point: Numeric | null;
  tenant_id: string;
}

export interface ModifierGroups {
  id: Generated<string>;
  max_select: number;
  min_select: number;
  name: string;
  tenant_id: string;
}

export interface ModifierRecipeLines {
  id: Generated<string>;
  inventory_item_id: string;
  modifier_id: string;
  qty_base_delta: Numeric;
  tenant_id: string;
}

export interface Modifiers {
  group_id: string;
  id: Generated<string>;
  name: string;
  price_delta: number;
  sort_order: number;
  tenant_id: string;
}

export interface NotificationDeliveries {
  alert_id: string | null;
  channel: string;
  id: Generated<string>;
  sent_at: Generated<Timestamp>;
  status: string;
  tenant_id: string;
  user_id: string;
}

export interface NotificationSettings {
  channel: string;
  digest_time: string;
  enabled: boolean;
  event_type: string;
  id: Generated<string>;
  quiet_end: string | null;
  quiet_start: string | null;
  recipients: string;
  tenant_id: string;
}

export interface PairingCodes {
  branch_id: string;
  code: string;
  created_by: string;
  expires_at: Timestamp;
  tenant_id: string;
}

export interface PaymentEvents {
  error: string | null;
  id: Generated<string>;
  invoice_id: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  provider_event_id: string;
  received_at: Generated<Timestamp>;
  tenant_id: string | null;
  type: string;
}

export interface PaymentMethods {
  billing_customer_id: string;
  brand: string | null;
  expires: string | null;
  id: Generated<string>;
  is_default: boolean;
  last4: string | null;
  provider_method_id: string | null;
  tenant_id: string;
  type: string;
}

export interface Payments {
  amount: number;
  change_given: number | null;
  id: Generated<string>;
  method: string;
  reference: string | null;
  sale_id: string;
  tenant_id: string;
  tendered: number | null;
}

export interface Permissions {
  code: string;
  group_name: string;
  label: string;
}

export interface PinLockouts {
  device_id: string;
  failed_count: Generated<number>;
  locked_until: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlanPrices {
  id: Generated<string>;
  plan_id: string;
  price_monthly: number;
  price_yearly: number;
  provider_price_id: string | null;
  valid_from: Timestamp;
  valid_until: Timestamp | null;
  version: number;
}

export interface Plans {
  features: Json;
  id: Generated<string>;
  max_branches: number;
  max_devices: number;
  max_users: number | null;
  name: string;
  price_monthly: number;
  price_yearly: number;
}

export interface PlatformAuditLog {
  action_code: string;
  after: Json | null;
  before: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  grant_id: string | null;
  happened_at: Timestamp;
  id: Generated<string>;
  ip_address: string;
  is_sensitive: boolean;
  reason: string | null;
  sentence: string;
  staff_id: string | null;
  target_tenant_id: string | null;
}

export interface PlatformPermissions {
  code: string;
  label: string;
}

export interface PlatformRolePermissions {
  permission_code: string;
  role_id: string;
}

export interface PlatformRoles {
  id: Generated<string>;
  name: string;
  summary: string;
}

export interface PlatformSessions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_address: string;
  last_seen_at: Generated<Timestamp>;
  pending_totp_secret_enc: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  staff_id: string;
  stage: string;
  token_hash: string;
}

export interface PlatformUsers {
  created_at: Generated<Timestamp>;
  email: string;
  failed_sign_in_count: Generated<number>;
  id: Generated<string>;
  last_active_at: Timestamp | null;
  locked_until: Timestamp | null;
  name: string;
  password_hash: string;
  role_id: string;
  status: string;
  totp_secret_enc: string | null;
}

export interface ProductModifierGroups {
  modifier_group_id: string;
  product_id: string;
  tenant_id: string;
}

export interface Products {
  category_id: string;
  id: Generated<string>;
  is_visible_on_pos: boolean;
  name: string;
  price: number;
  sort_order: number;
  tenant_id: string;
  updated_at: Timestamp;
  updated_by: string;
}

export interface PurchaseOrderLines {
  id: Generated<string>;
  item_id: string;
  po_id: string;
  qty_ordered: Numeric;
  qty_received: Numeric;
  tenant_id: string;
  unit_cost: number;
}

export interface PurchaseOrders {
  approved_by: string | null;
  branch_id: string;
  cancelled_at: Timestamp | null;
  created_by: string;
  delivery_fee: number;
  expected_date: Timestamp | null;
  id: Generated<string>;
  note: string | null;
  number: string;
  sent_at: Timestamp | null;
  status: string;
  subtotal: number;
  supplier_id: string;
  tenant_id: string;
  total: number;
}

export interface RecipeLines {
  id: Generated<string>;
  inventory_item_id: string;
  product_id: string;
  qty_base: Numeric;
  tenant_id: string;
}

export interface RefundLines {
  amount: number;
  id: Generated<string>;
  qty: number;
  refund_id: string;
  sale_line_id: string;
  tenant_id: string;
}

export interface Refunds {
  amount: number;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reason: string;
  requested_by: string;
  sale_id: string;
  tenant_id: string;
}

export interface RegisterSessions {
  approved_by: string | null;
  branch_id: string;
  client_created_at: Timestamp;
  closed_at: Timestamp | null;
  closed_by: string | null;
  counted_cash: number | null;
  device_id: string | null;
  expected_cash: number | null;
  id: Generated<string>;
  note: string | null;
  opened_at: Generated<Timestamp>;
  opened_by: string;
  opening_float: number;
  status: string;
  synced_at: Timestamp | null;
  tenant_id: string;
  variance: number | null;
}

export interface RolePermissions {
  permission_code: string;
  role_id: string;
  tenant_id: string;
}

export interface Roles {
  id: Generated<string>;
  is_locked: boolean;
  name: string;
  summary: string;
  tenant_id: string;
}

export interface SaleDiscounts {
  amount: number;
  approved_by: string | null;
  id: Generated<string>;
  id_number: string | null;
  percent: Numeric;
  sale_id: string;
  tenant_id: string;
  type: string;
}

export interface SaleLineModifiers {
  id: Generated<string>;
  modifier_id: string;
  name_snapshot: string;
  price_delta: number;
  sale_line_id: string;
  tenant_id: string;
}

export interface SaleLines {
  id: Generated<string>;
  line_total: number;
  name_snapshot: string;
  product_id: string;
  qty: number;
  sale_id: string;
  tenant_id: string;
  unit_price: number;
}

export interface Sales {
  branch_id: string;
  cashier_id: string;
  client_created_at: Timestamp;
  device_id: string | null;
  discount_total: number;
  id: Generated<string>;
  receipt_no: string;
  session_id: string;
  status: string;
  subtotal: number;
  synced_at: Timestamp | null;
  tenant_id: string;
  total: number;
  vat_amount: number;
  void_reason: string | null;
  voided_by: string | null;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  device_id: string | null;
  id: Generated<string>;
  ip_address: string;
  last_seen_at: Generated<Timestamp>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  surface: string;
  tenant_id: string;
  token_hash: string;
  user_id: string;
}

export interface StockCountLines {
  count_id: string;
  counted_qty: Numeric;
  expected_qty: Numeric;
  id: Generated<string>;
  item_id: string;
  tenant_id: string;
}

export interface StockCounts {
  branch_id: string;
  counted_by: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  started_at: Timestamp;
  status: string;
  tenant_id: string;
}

export interface StockMovements {
  approved_by: string | null;
  batch_id: string | null;
  branch_id: string;
  client_created_at: Timestamp;
  device_id: string | null;
  id: Generated<string>;
  item_id: string;
  note: string | null;
  qty_delta: Numeric;
  reason: string;
  source_id: string | null;
  source_type: string;
  synced_at: Timestamp | null;
  tenant_id: string;
  user_id: string | null;
}

export interface Subscriptions {
  billing_cycle: string;
  cancel_at: Timestamp | null;
  current_period_end: Timestamp;
  grace_until: Timestamp | null;
  id: Generated<string>;
  plan_id: string;
  plan_price_id: string;
  provider: string;
  provider_subscription_id: string | null;
  status: string;
  tenant_id: string;
  trial_ends_at: Timestamp | null;
}

export interface SupplierItems {
  is_default: boolean;
  item_id: string;
  last_cost: number;
  last_cost_at: Timestamp | null;
  pack_size: Numeric;
  pack_unit: string;
  supplier_id: string;
  supplier_sku: string | null;
  tenant_id: string;
}

export interface Suppliers {
  contact_name: string;
  email: string;
  id: Generated<string>;
  is_active: boolean;
  lead_time_days: number;
  min_order: number;
  name: string;
  order_days: string[];
  phone: string;
  tenant_id: string;
  terms: string;
}

export interface SupportAccessGrants {
  approved_by: string | null;
  duration_minutes: number;
  ended_by: string | null;
  ends_at: Timestamp | null;
  id: Generated<string>;
  reason: string;
  requested_at: Timestamp;
  scope: string;
  staff_id: string;
  starts_at: Timestamp | null;
  status: string;
  tenant_id: string;
  ticket_id: string | null;
}

export interface SupportTicketMessages {
  author_staff_id: string | null;
  author_user_id: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  tenant_id: string;
  ticket_id: string;
}

export interface SupportTickets {
  app_version: string | null;
  assignee_id: string | null;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  id: Generated<string>;
  number: string;
  requester_id: string;
  solved_at: Timestamp | null;
  status: string;
  subject: string;
  tenant_id: string;
}

export interface TenantEvents {
  detail: Json;
  happened_at: Timestamp;
  id: Generated<string>;
  reason: string | null;
  staff_id: string | null;
  tenant_id: string;
  type: string;
}

export interface TenantFeatureOverrides {
  flag_key: string | null;
  id: Generated<string>;
  limit_name: string | null;
  reason: string;
  set_by: string;
  tenant_id: string;
  until: Timestamp | null;
  value: Json;
}

export interface TenantPaymentMethods {
  id: Generated<string>;
  is_enabled: boolean;
  method: string;
  requires_reference: boolean;
  sort_order: number;
  tenant_id: string;
}

export interface Tenants {
  accent_hex: string;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  signup_source: string | null;
  status: string;
  suspended_reason: string | null;
  timezone: string;
  tin: string | null;
}

export interface UserAssignments {
  branch_id: string | null;
  id: Generated<string>;
  role_id: string;
  tenant_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  failed_sign_in_count: Generated<number>;
  id: Generated<string>;
  last_active_at: Timestamp | null;
  locked_until: Timestamp | null;
  name: string;
  password_hash: string | null;
  pin_hash: string | null;
  status: string;
  tenant_id: string;
}

export interface DB {
  alert_reads: AlertReads;
  alerts: Alerts;
  announcement_reads: AnnouncementReads;
  announcements: Announcements;
  app_releases: AppReleases;
  audit_log: AuditLog;
  auth_tokens: AuthTokens;
  batches: Batches;
  billing_customers: BillingCustomers;
  branches: Branches;
  cash_counts: CashCounts;
  cash_movements: CashMovements;
  categories: Categories;
  credit_notes: CreditNotes;
  data_requests: DataRequests;
  device_error_reports: DeviceErrorReports;
  devices: Devices;
  discount_rules: DiscountRules;
  feature_flags: FeatureFlags;
  goods_receipt_lines: GoodsReceiptLines;
  goods_receipts: GoodsReceipts;
  inventory_items: InventoryItems;
  invoice_lines: InvoiceLines;
  invoices: Invoices;
  item_branch_settings: ItemBranchSettings;
  modifier_groups: ModifierGroups;
  modifier_recipe_lines: ModifierRecipeLines;
  modifiers: Modifiers;
  notification_deliveries: NotificationDeliveries;
  notification_settings: NotificationSettings;
  pairing_codes: PairingCodes;
  payment_events: PaymentEvents;
  payment_methods: PaymentMethods;
  payments: Payments;
  permissions: Permissions;
  pin_lockouts: PinLockouts;
  plan_prices: PlanPrices;
  plans: Plans;
  platform_audit_log: PlatformAuditLog;
  platform_permissions: PlatformPermissions;
  platform_role_permissions: PlatformRolePermissions;
  platform_roles: PlatformRoles;
  platform_sessions: PlatformSessions;
  platform_users: PlatformUsers;
  product_modifier_groups: ProductModifierGroups;
  products: Products;
  purchase_order_lines: PurchaseOrderLines;
  purchase_orders: PurchaseOrders;
  recipe_lines: RecipeLines;
  refund_lines: RefundLines;
  refunds: Refunds;
  register_sessions: RegisterSessions;
  role_permissions: RolePermissions;
  roles: Roles;
  sale_discounts: SaleDiscounts;
  sale_line_modifiers: SaleLineModifiers;
  sale_lines: SaleLines;
  sales: Sales;
  sessions: Sessions;
  stock_count_lines: StockCountLines;
  stock_counts: StockCounts;
  stock_movements: StockMovements;
  subscriptions: Subscriptions;
  supplier_items: SupplierItems;
  suppliers: Suppliers;
  support_access_grants: SupportAccessGrants;
  support_ticket_messages: SupportTicketMessages;
  support_tickets: SupportTickets;
  tenant_events: TenantEvents;
  tenant_feature_overrides: TenantFeatureOverrides;
  tenant_payment_methods: TenantPaymentMethods;
  tenants: Tenants;
  user_assignments: UserAssignments;
  users: Users;
}
